UC-Davis-molecular-computing/scadnano

README.md
lib/src/actions/actions.dart
lib/src/constants.dart
lib/src/middleware/local_storage.dart
lib/src/reducers/app_ui_state_reducer.dart
lib/src/reducers/load_dna_file_reducer.dart
lib/src/serializers.dart
lib/src/state/app_ui_state.dart
lib/src/state/bound_substrand.dart
lib/src/state/dna_design.dart
lib/src/state/modification.dart
lib/src/state/strand.dart
lib/src/util.dart
lib/src/view/design_main_strand.dart
lib/src/view/design_main_strand_modification_bound_substrand.dart
lib/src/view/design_main_strand_modifications.dart
lib/src/view/design_main_strands.dart
lib/src/view/menu.dart
web/scadnano-styles.css

Supports displaying (not yet creating) DNA modifications such as biotin, fluorophores, etc.

Dna modifications

---

lib/src/view/menu.dart
web/scadnano-styles.css

Fixes #225 and cleanup keyboard shortcut menu view code

Adds copy and paste to Edit menu dropdown

---

lib/src/middleware/dna_ends_move_start.dart
lib/src/middleware/helix_offsets_change.dart
lib/src/middleware/helix_remove.dart
lib/src/reducers/dna_design_reducer.dart
lib/src/reducers/helices_reducer.dart
lib/src/reducers/inline_insertions_deletions_reducer.dart
lib/src/state/dna_design.dart
lib/src/state/mouseover_data.dart
lib/src/view/design_main_helix.dart

SVG positions are now recalculated accurately

fixed bug in adjusting helix min_offset

---

lib/src/state/design.dart
lib/src/state/strand_maker.dart
test/other_unit_test.dart

Currently, the tests do not add helices to the design.

Adding StrandMaker class and tests.

---

lib/src/constants.dart
lib/src/view/menu.dart
lib/src/view/menu_dropdown_right.dart
lib/src/view/react_bootstrap.dart
web/scadnano-styles.css

Implements https://github.com/UC-Davis-molecular-computing/scadnano/pull/507#issuecomment-727685759

Add links to older version

---

lib/src/constants.dart

I modified backend URLs to use the https server

Changing backend URLs to https server

---

.github/workflows/gh-pages.yml
.github/workflows/release.yml
README.md

Since there are no changes to the application code, I don't think it is necessary to bump version

Update docs + workflow redirect from master to main

---

lib/src/constants.dart
lib/src/state/design.dart
lib/src/state/helix.dart
test/reducer_test.dart

Fixes #597 
Planning to Squash and merge this PR in order to reduce number of commits in Dev/Main

Issue 597 remove helix pitch and yaw

---

lib/src/view/menu_side.dart
web/scadnano-styles.css

Doesn't hide side view; instead stacks side view options.

#420 hide side view helix group menu when side view/main view slide is far to the left

---

lib/src/reducers/helices_reducer.dart
lib/src/view/design_main_strand.dart
test/helix_groups_test.dart

Reverts UC-Davis-molecular-computing/scadnano#636

Revert "#628 deleting helices when using multiple groups of helixes causes the saved .sc file to be an illegal design when opened"

---

lib/src/reducers/helices_reducer.dart
test/reducer_test.dart

Added a unit test to test for this scenario

Work In Progress: Fixes #677; adjusting helices view order should update view

---

lib/src/reducers/helices_reducer.dart
lib/src/util.dart

See https://github.com/UC-Davis-molecular-computing/scadnano/pull/682#discussion_r762030596

Add doc comments for reassign_svg_positions and helices_assign_svg

---

web/index.html

Design will still not autofit, but rope select and pencil works as expected.

#768 rope select does not select correct points on switching to new design

---

lib/src/middleware/oxdna_export.dart

Supports exporting extensions in oxDNA export, fixes #803.

fixes 803: support extensions in oxDNA export

---

lib/src/constants.dart
lib/src/view/design_main_strand.dart

fixed bug in setting domain name and bumped version

---

lib/src/actions/actions.dart
lib/src/constants.dart
lib/src/reducers/app_ui_state_reducer.dart
lib/src/serializers.dart
lib/src/state/app_ui_state.dart
lib/src/state/app_ui_state_storables.dart
lib/src/state/design.dart
lib/src/util.dart
lib/src/view/design_main.dart
lib/src/view/design_main_base_pair_lines.dart
lib/src/view/menu.dart
test/base_pairs_test.dart
web/scadnano-styles.css

Closes #829: optional base pair lines

closes #829: Optional base pair lines

---

lib/src/actions/actions.dart
lib/src/view/design_main_strand.dart
lib/src/view/design_main_strand_extension.dart
lib/src/view/design_main_strand_loopout.dart

closes #835: option to remove domain/extension/loopout color

closes #835: option to remove domain/extension/loopout color

---

lib/src/reducers/strands_reducer.dart
lib/src/view/potential_extensions_view.dart

Same issue as https://github.com/UC-Davis-molecular-computing/scadnano/pull/658

845 click dragging extension ends crashes

---

lib/src/reducers/strands_move_reducer.dart
lib/src/view/design_main_strand.dart
lib/src/view/design_main_strand_moving.dart

830 project crashes when control clicking to unselect strand on different helix groups1

---

lib/src/actions/actions.dart
lib/src/state/domain.dart
lib/src/state/extension.dart
lib/src/state/loopout.dart
lib/src/state/strand.dart
lib/src/state/strand_maker.dart
lib/src/state/substrand.dart
lib/src/view/design_main_strand.dart

Changed type of `label` to string.
#878

closes #878: change label type to string

---

lib/src/state/design.dart

fixes #883: fix bug where cannot draw strand bound to other strand

---

lib/src/actions/actions.dart
lib/src/reducers/helices_reducer.dart
lib/src/serializers.dart
lib/src/state/design.dart
lib/src/state/helix.dart
lib/src/util.dart
lib/src/view/design_side_helix.dart
lib/src/view/menu.dart
test/helix_relax_rolls_test.dart

Same as https://github.com/UC-Davis-molecular-computing/scadnano-python-package/issues/257
#843

843 automatically set helix rolls based on crossover locations relax the rolls

---

lib/src/state/helix.dart
test/helix_relax_rolls_test.dart

fixes #907: fix bug with relaxing helix rolls

---

lib/src/actions/actions.dart
lib/src/middleware/export_dna_sequences.dart
lib/src/state/export_dna_format.dart
lib/src/state/strand.dart
lib/src/state/substrand.dart
lib/src/view/design_main_strand.dart
test/idt_unit_test.dart

customize delimiter between domains in exported DNA sequences
#912

fixes #912: customize delimiter between domains in exported DNA sequences

---

lib/src/state/modification.dart
lib/src/view/design_main_strand.dart
lib/src/view/design_main_strand_modification.dart
test/idt_unit_test.dart

Handle internal modifications that go in between bases.
#913

closes #913: handle internal modifications that go in between bases

---

lib/src/state/modification.dart
lib/src/view/design_main_strand_modification.dart

Displays each internal modification between bases if it is not attached to a base.
#919

919 display internal modifications unattached to a base between bases

---

lib/src/actions/actions.dart
lib/src/reducers/selection_reducer.dart
lib/src/serializers.dart
lib/src/state/dialog.dart
lib/src/state/selectable.dart
lib/src/util.dart
lib/src/view/design.dart
lib/src/view/design_main_dna_sequence.dart
lib/src/view/menu.dart

Implements "Select all with same..." feature for strands only.
#882

closes #882: select all with same

---

json_schema.json
lib/src/constants.dart
lib/src/middleware/system_clipboard.dart
lib/src/state/design.dart
lib/src/state/modification.dart
lib/src/state/selectable.dart
lib/src/state/strand.dart
test/other_unit_test.dart
test/reducer_test.dart
web/examples/output_designs/2_staple_2_helix_modifications.sc
web/examples/output_designs/2_staple_2_helix_origami_deletions_insertions_mods.sc
web/examples/output_designs/2_staple_2_helix_origami_deletions_insertions_mods_chained_methods.sc
web/examples/output_designs/many_helices_modifications.sc

Remove field `Modification.id`
#931

931 remove field modificationid

---

lib/src/constants.dart
lib/src/state/design.dart
lib/src/state/modification_type.dart
lib/src/view/design_footer.dart
test/reducer_test.dart

Deal with non-unique Modification vendor codes.
#934

closes #934: deal with non-unique Modification vendor codes

---

.github/workflows/dart.yml
.github/workflows/dart_formatting.yml
.github/workflows/gh-pages-dev.yml
.github/workflows/gh-pages.yml

Update `actions/checkout@v2` to `v3`

closes #917: change deploy action to use node16

---

lib/src/actions/actions.dart
lib/src/middleware/export_dna_sequences.dart

closes #964: exclude selected strands from export DNA sequences

---

lib/src/middleware/export_svg.dart

Made 5' extension exportable. The issue was that "transform-origin" and "transform-box" CSS styles were not cloned. After fixing this issue, I also had to make a new method for it to be compatible with PowerPoint. So when exporting a 5' extension, it would not work on PowerPoint unless "export svg text separately (PTT)" is enabled.
Closes issue #942
An example strand:
Exported SVG:
SVG in PowerPoint:

Fixes export 5' end of extension

---

lib/src/state/dialog.dart
lib/src/view/design_main_strand_crossover.dart
lib/src/view/design_main_strand_extension.dart
lib/src/view/design_main_strand_insertion.dart
lib/src/view/design_main_strand_loopout.dart
pubspec.lock
pubspec.yaml

closes #980: remove smart_dialog package dependency
