gh-pages.sh

This should make deployment commits on gh-pages easier to track.

Add comment to use -m flag when using peanut

---

lib/src/actions/actions.dart
lib/src/reducers/app_ui_state_reducer.dart
lib/src/serializers.dart
lib/src/state/app_ui_state.dart
lib/src/view/design_side.dart
lib/src/view/design_side_helix.dart
lib/src/view/menu.dart

Adds menu option under view named 'Show grid coordinates in side view' to display grid coordinates in smaller font under helix indexes.

add menu option to optionally show grid coordinates in side view; closes #102

---

lib/src/actions/actions.dart
lib/src/middleware/local_storage.dart
lib/src/reducers/app_ui_state_reducer.dart
lib/src/serializers.dart
lib/src/state/app_ui_state.dart
lib/src/view/menu.dart

Adding feature under 'Files' in menu that allows users to enable or disable saving DNA designs into local storage.

add option to save/not save DNADesign in localStorage on every edit; closes 348

---

clean.sh
lib/src/middleware/.gitignore
lib/src/state/.gitignore
lib/src/state/dna_design.dart
test/reducer_test.dart

If the max_offsets of helices are not specified, make the max_offset the same for every helix (by setting it equal to the max end of domain).

make default max_offset on every helix equal to the max end of domain on any helix; closes #351

---

lib/src/view/edit_mode.dart
test/reducer_test.dart

Updating state to unselect all items when switching out of select mode. Added test case for future reference as well.

unselect strands when switching out of select mode; closes #389

---

build.yaml
lib/src/app.dart

Fixes #399 (in terms of disabling redux dev tools) react dev tools will still work

Disable redux dev tools for release

---

.github/workflows/dart.yml

This allows CI checks to run on PRs made by external users. This should slightly reduce the frequency of CI tests running because not every push will trigger a build.

Modify CI UT workflow so it only run on PRs

---

lib/src/view/design_main_strand.dart
lib/src/view/design_main_strand_domain.dart
lib/src/view/design_main_strand_paths.dart
lib/src/view/design_main_strands.dart

Remove passing in app's "currently moving" state via props and instead
directly access the global model from the view.
This makes it so that only the strand that gets selected is rerendered.

Performance improvement for strand selection

---

.github/workflows/gh-pages.yml
lib/src/constants.dart

Tested in Fork: https://unhumbleben.github.io/scadnano/v0.11.3/
Here is example of when version number cannot be parsed: https://github.com/UnHumbleBen/scadnano/actions/runs/358816601
Root deployment still runs, but version url gets skipped and a warning message is fired so that we know we need to fix the version string.

Fixes #490; store old versions of scadnano at version-specific URLs

---

lib/src/constants.dart
lib/src/view/strand_color_picker.dart

JS bindings were not setup properly so function name was not
recognized by dart2js compiled code

Fixes #512; fix strand color picker

---

.github/workflows/gh-pages.yml
lib/src/constants.dart
lib/src/view/menu.dart

Tested Workflow: https://unhumbleben.github.io/scadnano/v0.15.2/
This was deployed via the `github-pages` action. Note that "v" is properly placed in the directory name

Fixes #571; fix workflow/links for older versions

---

README.md

The previous README description was the outdated coordinate system before the fix to #488. This change was missed in the original fix in #499.

Correct coordinate description by swapping x and z

---

.github/workflows/release.yml

Fix release note workflow by upgrading marvinpinto/action-automatic-releases from v1.1.0 to v1.2.1
#699 
Ran the updated job on my fork and verified that the [job succeeded](https://github.com/UnHumbleBen/scadnano/runs/4542338732?check_suite_focus=true) and [the release note was generated](https://github.com/UnHumbleBen/scadnano/releases/tag/latest).
Verify that all other workflows have been disabled to avoid rerunning then unnecessarily. Only the "release" workflow should be enabled.

Fixes #699; Fix release note workflow

---

.github/workflows/release.yml
lib/src/view/helix_group_moving.dart

Fix release note workflow by upgrading marvinpinto/action-automatic-releases from v1.1.0 to v1.2.1
#699 
Ran the updated job on my fork and verified that the [job succeeded](https://github.com/UnHumbleBen/scadnano/runs/4542338732?check_suite_focus=true) and [the release note was generated](https://github.com/UnHumbleBen/scadnano/releases/tag/latest).
Verify that all other workflows have been disabled to avoid rerunning then unnecessarily. Only the "release" workflow should be enabled.

Fixes #699; Fix release note workflow and run workflow for v0.17.0

---

lib/src/actions/actions.dart
lib/src/dna_file_type.dart
lib/src/reducers/load_dna_file_reducer.dart
lib/src/serializers.dart
lib/src/util.dart
lib/src/view/menu.dart

Replace the DNAFileType `enum` with a DNAFileType `EnumClass`.
This fixes #697, which was caused by the OverReactReduxDevToolsMiddleware failing to find a serializer for DNAFileType. Rewriting DNAFileType as a `EnumClass` resolves this issue.
Built locally and verified that the warning message is gone.

Fixes #697; fix JSON encoding warning on startup

---

lib/src/reducers/strands_reducer.dart
test/utils.dart

Change `move_strand` logic so that the current group's view order inverse map is only accessed if the strand is not moving.
#668
`move_strand` is used for displaying selected strands as well as moving strands. Moving strands requires accessing the current helix group's inverse view order map in order to determine what helix to move the strand. This logic works fine in the case of moving strands, but breaks when displaying selected strands because when selected strands are in different groups, the strands that are not in the current group will not belong to a helix that is contained in the current group's inverse view order map, leading to the error message in the issue linked above. Since the inverse view order map is only needed for the use case when the strand is actually moving, the …

Fixes #668; fix crash error when deselecting strand while strands from multiple helix groups are selected

---

.github/workflows/dart.yml

Modify Dart CI so that unit tests only run on PRs ready for review (not a draft). This will give us more control over when unit tests are executed. To prevent accidental merges, the job will fail whenever the PR is in draft. This ensures PR does not pass the checks unless unit tests have actually ran.
This is implemented using this solution: https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/16 and https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/20
#686 
Currently, unit tests are executed on every change made to a PR. This can be wasteful when a PR is a work in progress and unit tests are not needed anyways. This change will allow us to more judiciously pick when to run unit tests. We can now make PR a draft to disable unit tests. 
Verified …

Closes #686; Don't run unit tests on draft/incomplete PRs

---

lib/src/reducers/change_loopout_length.dart
lib/src/reducers/nick_ligate_join_by_crossover_reducers.dart
lib/src/reducers/strands_reducer.dart
lib/src/state/strand.dart
lib/src/state/strand_maker.dart
test/reducer_test.dart

- Replaced Strand.sequence getter with memoized getter.
- Refactor `Strand.initialize()` into smaller functions to improve readability and code reuse
- Add logic to Strand.initialize to maintain the following invariants:
- Either all substrands dna sequence are null or none of them are null
- If substrand has dna sequence, it will be same length as substrand length (question marks padding)
- ~~loopout_length_change_reducer and single_strand_dna_ends_commit_stop_reducer logic needed to be updated with to call set_sequence with the old_sequence as an argument to re-set the sequences of substrands.~~ (after meeting with Dave we decided that sequence changes should be kept local for more intuitive behavior)
- [`nick_reducer()` is simplified and no longer requires logic dealing with …

Fixes #492; Refactor Dart data model: store DNA sequence in domains and loopouts, rather in strand

---

CONTRIBUTING.md
lib/src/reducers/inline_insertions_deletions_reducer.dart
lib/src/state/design.dart
lib/src/state/helix.dart
lib/src/state/strand_maker.dart
lib/src/view/design_main_helix.dart
test/assign_dna_unit_test.dart
test/assign_domain_name_complement_domain_test.dart
test/assign_domain_name_complement_strand_test.dart
test/assign_strand_name_unit_test.dart
test/circular_strands_unit_test.dart
test/domain_label_move_test.dart
test/export_cadnano_v2_test.dart
test/helix_rotation_set_test.dart
test/idt_unit_test.dart
test/inline_insertions_deletions_test.dart
test/join_strands_by_crossovers_test.dart
test/move_linker_test.dart
test/other_unit_test.dart
test/oxdna_export_test.dart
test/paste_test.dart
test/reducer_test.dart

Fixed bug with Undo after "Inline insertions/deletions".
#761 
Opened the design described in the issue and ensured that expected behavior happens. I'm also going to add unit tests. (Hence this PR being a draft for now.)

fixes #761: undo "inline insertions/deletions" should undo setting of helix tick marks

---

lib/src/view/design_main_error_boundary.dart

I don't know if this covers all scenarios where an error pops up. So far it works as expected when a component in `view/` throws.

793 remove loading message when program crashes

---

lib/src/state/design_side_rotation_data.dart

closes #834: helix backbone arrows should be color of Domain if defined

closes #834: helix backbone arrows should be color of Domain if defined

---

lib/src/constants.dart

Successfully hosted scripts on https://scadnano-backend.onrender.com/
According to [Render](https://render.com/docs/free#free-web-services), the free service will "spin down" after 15 minutes of inactivity, and will take up to 30 seconds to spin up again upon request. I found it takes about ~10 seconds for our particular scripts, so if that's acceptable, we can use this as a fix.

fixes #842: Move Autostaple scripts to new cloud service

---

CONTRIBUTING.md
lib/src/actions/actions.dart
lib/src/reducers/strands_reducer.dart
lib/src/serializers.dart
lib/src/state/dialog.dart
lib/src/state/selectable.dart
lib/src/view/design_footer.dart
lib/src/view/design_main_strand.dart
lib/src/view/design_main_strand_extension.dart
lib/src/view/design_main_strand_loopout.dart

Added right-click menu items for editing labels.
#469
Previously users could only edit labels in the Python package or by manually editing the `.sc` file.
I tried out the new menu items and verified that edits properly update the design.

469 add ability to edit domainstrandloopout labels

---

lib/src/actions/actions.dart
lib/src/middleware/export_dna_sequences.dart
lib/src/state/dialog.dart
lib/src/state/export_dna_format.dart
lib/src/state/export_dna_format_strand_order.dart
lib/src/view/design_dialog_form.dart
lib/src/view/menu.dart
test/idt_unit_test.dart

Implemented ability to specify row-major order of wells when exporting plates.
#874 
This is a common option when specifying plates.
Tried it with the example 6-helix origami rectangle.

874 option to use row major order in plates

---

lib/src/middleware/assign_dna.dart
lib/src/reducers/assign_or_remove_dna_reducer.dart
lib/src/reducers/strands_reducer.dart
lib/src/state/design.dart

Prevents assigning DNA complements when there is an unpaired insertion or deletion.
#884 
The error given before this fix was confusing. This more directly indicates the problem.

884 disallow assigning dna complements when there are unpaired deletionsinsertions

---

web/examples/output_designs/2_staple_2_helix_origami_deletions_insertions_mods.sc

Partially addresses #921. This fixes the example design "2_staple_2_helix_origami_deletions_insertions_mods" to use the key `"5'-/5Biosg/"` instead of `"/5Biosg/"`, to match what future biotins added with the IDT text `"/5Biosg/"` would have as a key (with the `"5'-"` prepended). However, there's still some inconsistency with mixing mods added via the web interface (where `"5'-"` and `"3'-"` would be prepended to the key) versus created via the Python package (where the key could be something else).
#921

fixed example, but problem with #921 still remains

---

lib/src/view/menu_dropdown_item.dart
web/scadnano-styles.css

The issue was that the `float: right` CSS property on the keyboard shortcut element was causing the element's width to not be considered when computing the entire menu's width. This PR changes dropdown items to use flexbox with `justify-content: space-between` to align the keyboard shortcut to the right.

fixes #902: make menu dropdown wider for Edit-->Copy/Paste/Select

---

lib/src/view/design_main_strand.dart
lib/src/view/design_main_strand_extension.dart
lib/src/view/design_main_strand_loopout.dart

Fixes batch delete/set labels and names for domains and strands.
- Used ``BatchAction`` to group together set labels/name.
- Created ``get_selected_domains`` function that returns a ``BuiltSet<Domain>`` set, so setting domain names still work if 
user selects with domain tool
- Renamed some functions like ``set_substrand_names `` to ``set_domain_names``.

953 remove strand in batch

---

lib/src/actions/actions.dart
lib/src/constants.dart
lib/src/reducers/app_ui_state_reducer.dart
lib/src/serializers.dart
lib/src/state/app_ui_state.dart
lib/src/state/app_ui_state_storables.dart
lib/src/view/design_main.dart
lib/src/view/design_main_dna_sequences.dart
lib/src/view/design_main_strand.dart
lib/src/view/design_main_strand_crossover.dart
lib/src/view/design_main_strand_deletion.dart
lib/src/view/design_main_strand_dna_end.dart
lib/src/view/design_main_strand_domain.dart
lib/src/view/design_main_strand_extension.dart
lib/src/view/design_main_strand_insertion.dart
lib/src/view/design_main_strand_loopout.dart
lib/src/view/design_main_strand_modification.dart
lib/src/view/design_main_strand_modifications.dart
lib/src/view/design_main_strand_paths.dart
lib/src/view/design_main_strands.dart
lib/src/view/menu.dart
web/scadnano-styles.css

Adds menu option "Retain strand color on selection" in the View menu. When this is enabled, strands are not shown in hot pink when selected, but still have the shadow effect and a slightly larger stroke width. Works by using a different CSS class depending on the option.

 closes #870: Feature request: selection preserves color

---

lib/src/view/design_main_strand_extension.dart
lib/src/view/design_main_strand_paths.dart

fixes #959: display DNA sequence on extension in order 5' to 3'.
This is done by always drawing the path for the extension 5' to 3'. Previously we drew it left-to-right, but in cases where the 3' end is to the left of the 5' end, this helped display the extension name/label right-side up, but caused the sequence to appear backward. Since the DNA sequence issue is more serious and could lead to mistakes in the design, for now we'll favor fixing that, and make separate issues to deal with
1. Displaying extension name/label right-side up in all cases.
2. Displaying DNA sequence right-side up. Currently, for cases where the 3' end is to the left of the 5' end, just like the default for reverse domains, the DNA sequence is displayed in the correct order but upside down. We'll need a separate …

fixes #959: display DNA sequence on extension in order 5' to 3'

---

lib/src/actions/actions.dart
lib/src/constants.dart
lib/src/middleware/export_svg.dart
lib/src/reducers/app_ui_state_reducer.dart
lib/src/serializers.dart
lib/src/state/app_ui_state.dart
lib/src/state/app_ui_state_storables.dart
lib/src/state/base_pair_display_type.dart
lib/src/state/dialog.dart
lib/src/view/design_main.dart
lib/src/view/design_main_base_pair_rectangle.dart
lib/src/view/menu.dart

Created a new display option for base pairs: rectangle.
Moved changed the display into a dialog box.
The dialogue box.
The display when display with rectangle and even if mismatched as false.

#897 option to display rectangle

---

lib/src/actions/actions.dart
lib/src/middleware/oxdna_export.dart
lib/src/reducers/app_ui_state_reducer.dart
lib/src/serializers.dart
lib/src/state/app_ui_state.dart
lib/src/state/app_ui_state_storables.dart
lib/src/state/strand.dart
lib/src/view/menu.dart

closes #588: export to oxView format

---

lib/src/view/design_main_dna_sequence.dart

Fixes letter spacing for all font types by switching back to textLength as opposed to letterSpacing.
We can see that the screenshot in #974, the user is using "Lucida Console", which explains the misalignment because the letterSpacing value is hardcoded for "Consolas" font. The fix the bug, we just switched back to using textLength.

Closes #974 DNA misalignment

---

lib/src/state/design.dart
lib/src/state/design_side_rotation_data.dart
lib/src/state/helix.dart
lib/src/view/design_side_rotation.dart

996 display backbone angle correctly when `Geometry.base_pairs_per_turn` is not 10.5

---

lib/src/view/design.dart

There was an error with the boolean logic on line 646 of `design.dart`. This was preventing the Chrome Dev Tools key shortcut from opening. Looking through the code, the dev tools opens on other browsers like Arc (F12) and Firefox (F12). I found out that the logic for detecting keyboard presses works properly in `index.html` so I dug deeper through the code. It turns out that `design.dart` was firing when it should not have been, preventing the default behaviour of `CTRL + SHIFT + I`.
Fixes #998. This also fixes other issues where different hotkeys `CTRL + I` or `SHIFT + I` would also toggle insertion mode.
To reproduce the issue;
1) The Select (S) or Rope Select (R) tools must be enabled.
2) From there, press `CTRL + SHIFT + I`.
3) The insertion tool (ALT + I), will be selected.
For this …

Fixed #998 - Fixed a boolean logic error on line 646 of design.dart

---

lib/src/view/design_dialog_form.dart
web/scadnano-styles.css

I added CSS to right justify the input in labels for the dialog box.
Fixes #999. Input is now right-justified.
Fixes #999.
Originally, the fix affected ALL dialogs, but I changed it to only affect dialogs and labels with inputs. This was tested on Windows 11, Chrome.
I am currently unsure of other forms of dialog boxes, but the two that I tested were;
**File -> Load Example**
**Edit -> Set Geometric Parameters**

Fixed #999 - Right Justified Right Fields in Dialogs with Inputs

---

.github/workflows/dart.yml
.github/workflows/dart_formatting.yml
.github/workflows/gh-pages-dev.yml
.github/workflows/gh-pages.yml
CONTRIBUTING.md
analysis_options.yaml
lib/src/json_serializable.dart
lib/src/middleware/export_cadnano_file.dart
pubspec.lock
pubspec.yaml
test/export_cadnano_v2_test.dart
test/reducer_test.dart

This change adds support for Dart 3. However, there is some dependency overrides added to fix some issues. I have not yet found a way to solve this issue without adding the dependency override.
**Furthermore**, it is still failing `export_cadnano_v2_test.dart`.
Fixes #990 
This is to hopefully solve the long build times, but most importantly place the repository on the current dart dependency. This brings everything up to date.
This was tested on Windows 11, using **Dart 3.5.4**. The browsers I used were Firefox and Google Chrome. Since the JSONEncoder became a final class, we couldn't extend it anymore. We had to re-implement the JsonEncoder in our own way.

Fixes #990 - Upgrade to Dart 3

---

lib/src/view/design_main_strand.dart
lib/src/view/design_main_strand_dna_end.dart

When one end of a strand is clicked, the default option is that end. Fixed by making it similar to add_modification. Did not add unit tests.

default extension location fixed

---

pubspec.lock
web/scadnano-styles.css

I changed some CSS to be more in-line with what #988 was wanting to fix. However, it also ended up changing the "import cadnano v2" button as well. I looked elsewhere, and this appears to be the only item changing, but I am not sure if I am missing some other place this could have affected it.
As for #988, "Open" was not lined up with "Save". You can view this by clicking `File` in the navigation bar.
This fixes #988.
This was tested on both Firefox and Chrome, on Windows 11. This shouldn't affect the unit tests, and all unit tests have passed when updating the CSS. As for other ramifications, it appears as this only affects the "Open" and "Import cadnano v2" buttons in the File navigation menu. I have looked in other places, and it all otherwise looks identical to the current dev branch.

Fixes #988 - Fix Appearance of File -> Open

---

.github/workflows/dart.yml
.github/workflows/dart_formatting.yml
.github/workflows/gh-pages-dev.yml
.github/workflows/gh-pages.yml
CONTRIBUTING.md

This updates the dart version in the GitHub actions file(s) to the version specified by `pubspec.yaml`.
This fixes #1023.
The actions were failing in the dev branch because of a mismatch between the Dart versions and the `pubspec.yaml` versions. The issue is specified at #1023.
I was researching possible solutions to make updating to the latest dart version easier, and came across [this](https://github.com/dart-lang/setup-dart). It's a GitHub action created by the Dart team to automatically download and install the latest (or a specific) version of Dart.
As for testing, you can view the actions below to see that they both work and pass. **However** there is a big caveat. I have also updated the `.github/workflows/gh-pages.yml` and `.github/workflows/gh-pages-dev.yml` with this. I am …

Fixes #1023 - Update GitHub Actions Dart Version

---

.github/dependabot.yml
.github/workflows/dart.yml
.github/workflows/dart_formatting.yml
.github/workflows/gh-pages-dev.yml
.github/workflows/gh-pages.yml
CONTRIBUTING.md
pubspec.lock

This is a small change which adds dependabot support.
This fixes #1025.
Dependabot can help keep packages up-to-date. I noticed in the old PRs that some version of dependabot has existed before. Since this is a small change, please let me know if this is not necessary, it did not take much time to add!
There are some caveats, I believe if there is a major security vulnerability, it will bypass the `dev` branch, and make a direct PR for the `main` branch instead. Otherwise, under normal circumstances, it should make a PR for the `dev` branch only.

Fixes #1025  - Add Dependabot Support
